# Generated by Django 4.1.2 on 2022-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("post_image", models.ImageField(upload_to="")),
                ("like", models.IntegerField(default=0)),
                ("read", models.IntegerField(default=0)),
                ("readtxt", models.TextField()),
            ],
        ),
    ]
